cargo-features = ["named-profiles"]

[workspace]
members = [
	"integration-tests",
	"node/cli",
	"node/primitives",
	"node/rpc",
	"node/service",
	"pallets/bancor",
	#"pallets/bid",
	"pallets/flexible-fee",
	"pallets/lightening-redeem",
	"pallets/liquidity-mining",
	"pallets/minter-reward",
	"pallets/salp",
	"pallets/salp-lite",
	"pallets/token-issuer",
	"pallets/vesting",
	"pallets/vsbond-auction",
	"pallets/vtoken-mint",
	"pallets/vtoken-mint/rpc",
	"pallets/call-switchgear",
	"pallets/parachain-staking",
	"runtime/bifrost-kusama",
	"runtime/bifrost-polkadot",
	"xcm-support",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true

# The list of dependencies below (which can be both direct and indirect dependencies) are crates
# that are suspected to be CPU-intensive, and that are unlikely to require debugging (as some of
# their debug info might be missing) or to require to be frequently recompiled. We compile these
# dependencies with `opt-level=3` even in "dev" mode in order to make "dev" mode more usable.
# The majority of these crates are cryptographic libraries.
#
# Note that this does **not** affect crates that depend on Substrate. In other words, if you add
# a dependency on Substrate, you have to copy-paste this list in your own `Cargo.toml` (assuming
# that you want the same list). This list is only relevant when running `cargo build` from within
# the Substrate workspace.
#
# If you see an error mentioning "profile package spec ... did not match any packages", it
# probably concerns this list.
#
# This list is ordered alphabetically.
[profile.dev.package]
blake2 = { opt-level = 3 }
blake2-rfc = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
librocksdb-sys = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

[patch.crates-io]
zenlink-protocol = { git = "https://github.com/bifrost-finance/Zenlink-DEX-Module", rev = "e24926ccd75b6177d35c552006d961d66044f0cc"}
zenlink-protocol-rpc = { git = "https://github.com/bifrost-finance/Zenlink-DEX-Module", rev = "e24926ccd75b6177d35c552006d961d66044f0cc" }
zenlink-protocol-runtime-api = { git = "https://github.com/bifrost-finance/Zenlink-DEX-Module", rev = "e24926ccd75b6177d35c552006d961d66044f0cc" }
merkle-distributor = { git = "https://github.com/bifrost-finance/merkle-distributor", rev = "87e3635d937da111ae9422c40bca4d771dc3c166" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a51c4f7f04ec909dc14b3841de9014dfbc8d3600" }
orml-currencies = {git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a51c4f7f04ec909dc14b3841de9014dfbc8d3600" }
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a51c4f7f04ec909dc14b3841de9014dfbc8d3600" }
orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a51c4f7f04ec909dc14b3841de9014dfbc8d3600" }
orml-unknown-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a51c4f7f04ec909dc14b3841de9014dfbc8d3600" }
orml-xcm = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a51c4f7f04ec909dc14b3841de9014dfbc8d3600" }
orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a51c4f7f04ec909dc14b3841de9014dfbc8d3600" }