[package]
name = "bridge-hub-westend-emulated-chain"
version = "0.0.0"
authors = ["hqwangningbo <2536935847@qq.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Bridge Hub Westend emulated chain"
publish = false

[dependencies]
serde_json = "1.0.104"

# Substrate
sp-core = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }

# Polakadot
parachains-common = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true, default-features = false }
emulated-integration-tests-common = { workspace = true, default-features = false }
bridge-hub-westend-runtime = { workspace = true }
