[package]
name = "asset-hub-westend-emulated-chain"
version = "0.0.0"
authors = ["hqwangningbo <2536935847@qq.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Asset Hub Westend emulated chain"
publish = false

[dependencies]
serde_json = "1.0.104"

# Substrate
sp-core = { workspace = true }
sp-runtime = { workspace = true }
frame-support = { workspace = true }

# Polakadot
parachains-common = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
asset-hub-westend-runtime = { workspace = true }
westend-emulated-chain = { workspace = true }
