[package]
name = "brml-assets"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
parity-codec = { version = "4.1.1", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-support = { git = "https://github.com/paritytech/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }

[dev-dependencies]
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate", default-features = false }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"sr-primitives/std",
	"srml-support/std",
	"system/std",
	"rstd/std",
	"runtime-io/std",
	"substrate-primitives/std",
]
